name: CI Tools
on:
  workflow_dispatch:
  push:
    paths:
      - "tools/**"
jobs:
  test-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Install Nushell
        uses: hustcer/setup-nu@v3

      - name: Run tool tests
        run: |
          export NU_LIB_DIRS="$GITHUB_WORKSPACE/test"
          nu tools/run_all_tests.nu
